name = "textshare-sync"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "ROOM"
class_name = "Room"

[[durable_objects.bindings]]
name = "LIMIT"
class_name = "Limiter"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["Limiter"]

[observability]
enabled = true
